apply plugin: 'com.android.application'

static def versionCodeDate() {
    return new Date().format("yyyy.MM.dd_HH.mm")
}

android {
    signingConfigs {
        release {
        }
    }
    compileSdkVersion 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 34

        versionCode 15
        versionName ""
    }
    buildTypes {
        debug {
            buildConfigField "Boolean", "DEBUG_MODE", "true"

            versionNameSuffix versionCodeDate()

            setProperty("archivesBaseName", "tOndO_keyboard_" + versionNameSuffix)

            dependencies {
                def acraVersion = '5.7.0'
                implementation "ch.acra:acra-mail:$acraVersion"
                implementation "ch.acra:acra-notification:$acraVersion"
            }
        }
        release {
            buildConfigField "Boolean", "DEBUG_MODE", "false"

            versionNameSuffix "1.0.4"

            setProperty("archivesBaseName", "tOndO_keyboard_" + versionNameSuffix)

            minifyEnabled false
            shrinkResources false

            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            ndk {
                debugSymbolLevel 'SYMBOL_TABLE'
            }
        }
        profile {
            initWith debug
        }
    }
    namespace 'com.foschia.tondokeyboard'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.4.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.preference:preference:1.1.1'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'com.android.billingclient:billing:6.2.0'
    implementation 'com.google.guava:guava:31.1-android'
    
    // Flutter module dependencies
    debugImplementation 'com.foschia.flutter_ui:flutter_debug:1.0'
    profileImplementation 'com.foschia.flutter_ui:flutter_profile:1.0'
    releaseImplementation 'com.foschia.flutter_ui:flutter_release:1.0'
}

android.applicationVariants.all { variant ->
    variant.outputs.all {
        outputFileName = "tOndO_keyboard_${variant.versionName}-${variant.name}.apk"
    }
}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.1'
    }
}

String storageUrl = System.env.FLUTTER_STORAGE_BASE_URL ?: "https://storage.googleapis.com"
repositories {
    google()
    mavenCentral()
    maven {
        url '..\\..\\flutter_ui\\build\\host\\outputs\\repo'
    }
    maven {
        url "$storageUrl/download.flutter.io"
    }
}

def flutterModulePath = "../../flutter_ui"

task buildFlutterAar(type: Exec) {

    workingDir flutterModulePath
    if (System.properties['os.name'].toLowerCase().contains('windows')) {
        commandLine 'cmd', '/c', 'flutter', 'build', 'aar'
    } else {
        commandLine 'flutter', 'build', 'aar'
    }

    inputs.dir "${flutterModulePath}/lib"
    inputs.file "${flutterModulePath}/pubspec.yaml"

    outputs.dir "${flutterModulePath}/build/host/outputs/repo"
}

preBuild.dependsOn buildFlutterAar

