apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'com.android.application'

static def versionCodeDate() {
    return new Date().format("yyyy.MM.dd_HH.mm")
}

android {
    signingConfigs {
        release {
        }
    }
    compileSdkVersion 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdk 21
        targetSdk 36

        versionCode 19
        versionName ""
    }
    buildTypes {
        debug {
            buildConfigField "Boolean", "DEBUG_MODE", "true"

            versionNameSuffix versionCodeDate()

            setProperty("archivesBaseName", "tOndO_keyboard_" + versionNameSuffix)

            dependencies {
                def acraVersion = '5.7.0'
                implementation "ch.acra:acra-mail:$acraVersion"
                implementation "ch.acra:acra-notification:$acraVersion"
            }
        }
        release {
            buildConfigField "Boolean", "DEBUG_MODE", "false"

            versionNameSuffix "1.0.7.1"

            setProperty("archivesBaseName", "tOndO_keyboard_" + versionNameSuffix)

            minifyEnabled false
            shrinkResources false

            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            ndk {
                debugSymbolLevel 'SYMBOL_TABLE'
            }
        }
    }
    namespace 'com.foschia.tondokeyboard'
}

dependencies {
    implementation platform('org.jetbrains.kotlin:kotlin-bom:1.8.22')
    implementation 'org.jetbrains.kotlin:kotlin-stdlib'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation project(':unityLibrary')
    implementation fileTree(dir: project(':unityLibrary').getProjectDir().toString() + ('\\libs'), include: ['*.jar'])
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'com.android.billingclient:billing:8.0.0'
    implementation 'com.google.guava:guava:33.5.0-android'

}

android.applicationVariants.all { variant ->
    variant.outputs.all {
        outputFileName = "tOndO_keyboard_${variant.versionName}-${variant.name}.apk"
    }
}

buildscript {
    ext.kotlin_version = '1.8.22'

    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}