public enum PALETTE_ELEMENT 
{
    GLYPH_SYMBOL,
    GLYPH_CONSONANT,
    GLYPH_VOWEL,

    ACTION_BAR_BUTTON_BACKGROUND,
    ACTION_BAR_BUTTON_ICON,
    ACTION_BAR_DIRECTIONAL_BACKGROUND,
    ACTION_BAR_DIRECTIONAL_ICON,
    ACTION_BAR_BACKGROUND,

    TONDOS_EXTERIOR,
    TONDOS_INTERIOR,
    TONDOS_CAVITY,

    PERMANENT_BUTTON_BACKGROUND,
    PERMANENT_BUTTON_ICON,
    DONE_BACKGROUND,
    DONE_ICON,
    SHIFT_PRESSED_ICON,

    KEYBOARD_BACKGROUND,

    GLYPH_SELECTED,
    GLYPH_SELECTED_BACKGROUND,

    SHADOW,
    NONE
}
